export const GET_CHOCOLATES = "GET_CHOCOLATES";
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS";
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE";

export const GIFT_CHOCOLATE = "GIFT_CHOCOLATE";
export const GIFT_CHOCOLATE_SUCCESS = "GIFT_CHOCOLATE_SUCCESS";
export const GIFT_CHOCOLATE_FAILURE = "GIFT_CHOCOLATE_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";
